package net.unit8.bouncr.component.config;

public enum HookPoint {
    BEFORE_SIGN_UP,
    AFTER_SIGN_UP,
    BEFORE_CREATE_USER,
    AFTER_CREATE_USER,
    BEFORE_UPDATE_USER,
    AFTER_UPDATE_USER,
    BEFORE_DELETE_USER,
    AFTER_DELETE_USER,
    AFTER_CREATE_PASSWORD_CREDENTIAL,
    AFTER_UPDATE_PASSWORD_CREDENTIAL,
    AFTER_DELETE_PASSWORD_CREDENTIAL,
    AFTER_PASSWORD_RESET,
    BEFORE_PASSWORD_RESET_CHALLENGE,
    AFTER_PASSWORD_RESET_CHALLENGE,
    BEFORE_SIGN_IN,
    AFTER_SIGN_IN,
    ALLOWED_SIGN_IN,
    BEFORE_SIGN_OUT,
    AFTER_SIGN_OUT,
    BEFORE_VALIDATE_USER_PROFILES,
}
