export const ROUTES = {
  HOME: '/',
  SIGN_IN: '/sign_in',
  SIGN_IN_BY_OIDC: '/sign_in/oidc/:name',
  SIGN_OUT: '/sign_out',
  SIGN_UP: '/sign_up',
  CHANGE_PASSWORD: '/change_password',
  CHANGE_PROFILE: '/change_profile',
  RESET_PASSWORD_CHALLENGE: '/reset_password_challenge',
  RESET_PASSWORD: '/reset_password',
  USERS: '/admin/users',
  GROUPS: '/admin/groups',
  APPLICATIONS: '/admin/applications',
  REALMS: '/admin/realms',
  ROLES: '/admin/roles',
  PERMISSIONS: '/admin/permissions',
  OIDC_PROVIDERS: '/admin/oidc_providers',
  OIDC_APPLICATIONS: '/admin/oidc_applications',
  INVITATIONS: '/admin/invitations',
  AUDIT: '/audit',
  EMAIL_VERIFICATION: '/email_verification',
} as const;
